export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_MARKED = 'UPDATE_MARKED';
export const UPDATE_SELECTED = 'UPDATE_SELECTED';
export const UPDATE_COMPLETE = 'UPDATE_COMPLETE';
export const SET_INITIAL_DAYS = 'SET_INITIAL_DAYS';
export const UPDATE_NOTE_SUBMITTED = 'UPDATE_NOTE_SUBMITTED';
